/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ISyVue: typeof import('~icons/sy/vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyButton: typeof import('./../src/components/SyButton/index.vue')['default']
    TestComp: typeof import('./../src/components/TestComp.vue')['default']
  }
}
