/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    IconSelect: (typeof import("./../src/components/iconSelect.vue"))["default"];
    ISyVue: (typeof import("~icons/sy/vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SvgIcon: (typeof import("./../src/components/svgIcon.vue"))["default"];
  }
}
