/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default'];
    SyButton: typeof import('./../src/components/SyButton/index.vue')['default'];
    TestComp: typeof import('./../src/components/TestComp.vue')['default'];
  }
}
