/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    'IEp:expand': typeof import('~icons/ep/expand')['default'];
    'IEp:fold': typeof import('~icons/ep/fold')['default'];
    'IEp:switchButton': typeof import('~icons/ep/switch-button')['default'];
    ISyVue: typeof import('~icons/sy/vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SelectLang: typeof import('./../src/components/selectLang.vue')['default'];
    SvgIcon: typeof import('./../src/components/svgIcon.vue')['default'];
    SyButton: typeof import('./../src/components/syButton/index.vue')['default'];
    TestComp: typeof import('./../src/components/testComp.vue')['default'];
  }
}
